# -------- Stage 1: Build the app --------
FROM maven:3.9.6-eclipse-temurin-17 AS build

WORKDIR /app

# Copy all backend files
COPY . .

# Build jar
RUN mvn clean package -DskipTests

# -------- Stage 2: Run the app --------
FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

# Copy jar from build stage
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]