# MySQL Railway Connection
spring.datasource.url=jdbc:mysql://mainline.proxy.rlwy.net:42239/railway?useSSL=true&requireSSL=true&verifyServerCertificate=false
spring.datasource.username=root
spring.datasource.password=kHiLifHZOxrCoqXETZEcechfzBIpKtqW

# Driver (important)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8080